project_name: protoc-gen-go-mcp

before:
  hooks:
    - go mod tidy

builds:
  - id: protoc-gen-go-mcp
    main: ./cmd/protoc-gen-go-mcp
    binary: protoc-gen-go-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: stablekernel
    name: protoc-gen-go-mcp
  prerelease: auto
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

# Sign the checksum file for added security
signs:
  - artifacts: checksum