.PHONY: protoc-gen-go-mcp generate fmt $(GOLANG_SRCS)

PROTOS := $(shell find ./examples/protos -name *.proto)

GOLANG_SRCS := $(patsubst ./%,%,$(shell find . -path "*/cmd/protoc-gen-go-mcp/*.go"))

fmt: $(GOLANG_SRCS)
	@echo "Formatting files..."
	@gofmt -s -w $(GOLANG_SRCS) && goimports -w $(GOLANG_SRCS) && echo "Formatted successfully!"

protoc-gen-go-mcp:
	@echo "Building protoc-gen-go-mcp..."
	@go build -o $(GOPATH)/bin/protoc-gen-go-mcp ./cmd/protoc-gen-go-mcp && echo "Built successful!"

generate: protoc-gen-go-mcp
	@echo "Generating new files..."
	@protoc --go_out=. --go_opt=paths=source_relative $(PROTOS)
	@protoc --go-mcp_out=. --proto_path=examples/protos $(PROTOS) && echo "Generated successfully!"
	@$(MAKE) -s fmt