// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cmd/protoc-gen-go-mcp/testdata/schemapb/schema.proto

package schemapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Color is a plain enum used to test enum schema generation.
type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_RED         Color = 1
	Color_COLOR_GREEN       Color = 2
	Color_COLOR_BLUE        Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_RED",
		2: "COLOR_GREEN",
		3: "COLOR_BLUE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_RED":         1,
		"COLOR_GREEN":       2,
		"COLOR_BLUE":        3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescGZIP(), []int{0}
}

// Node is a recursive message, used to test that recursive messages are
// represented with $defs + $ref instead of looping forever.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value held by this node.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Child nodes.
	Children      []*Node `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Node) GetChildren() []*Node {
	if x != nil {
		return x.Children
	}
	return nil
}

// Inner is a plain nested message with no recursion, used for the "nested
// message" row.
type Inner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A string field on the nested message.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Inner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// AllScalars covers every scalar proto kind in the schema table.
type AllScalars struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A string field.
	SString string `protobuf:"bytes,1,opt,name=s_string,json=sString,proto3" json:"s_string,omitempty"`
	// A bytes field.
	SBytes []byte `protobuf:"bytes,2,opt,name=s_bytes,json=sBytes,proto3" json:"s_bytes,omitempty"`
	// A bool field.
	SBool bool `protobuf:"varint,3,opt,name=s_bool,json=sBool,proto3" json:"s_bool,omitempty"`
	// An int32 field.
	SInt32 int32 `protobuf:"varint,4,opt,name=s_int32,json=sInt32,proto3" json:"s_int32,omitempty"`
	// A sint32 field.
	SSint32 int32 `protobuf:"zigzag32,5,opt,name=s_sint32,json=sSint32,proto3" json:"s_sint32,omitempty"`
	// An sfixed32 field.
	SSfixed32 int32 `protobuf:"fixed32,6,opt,name=s_sfixed32,json=sSfixed32,proto3" json:"s_sfixed32,omitempty"`
	// A uint32 field.
	SUint32 uint32 `protobuf:"varint,7,opt,name=s_uint32,json=sUint32,proto3" json:"s_uint32,omitempty"`
	// A fixed32 field.
	SFixed32 uint32 `protobuf:"fixed32,8,opt,name=s_fixed32,json=sFixed32,proto3" json:"s_fixed32,omitempty"`
	// An int64 field.
	SInt64 int64 `protobuf:"varint,9,opt,name=s_int64,json=sInt64,proto3" json:"s_int64,omitempty"`
	// A sint64 field.
	SSint64 int64 `protobuf:"zigzag64,10,opt,name=s_sint64,json=sSint64,proto3" json:"s_sint64,omitempty"`
	// An sfixed64 field.
	SSfixed64 int64 `protobuf:"fixed64,11,opt,name=s_sfixed64,json=sSfixed64,proto3" json:"s_sfixed64,omitempty"`
	// A uint64 field.
	SUint64 uint64 `protobuf:"varint,12,opt,name=s_uint64,json=sUint64,proto3" json:"s_uint64,omitempty"`
	// A fixed64 field.
	SFixed64 uint64 `protobuf:"fixed64,13,opt,name=s_fixed64,json=sFixed64,proto3" json:"s_fixed64,omitempty"`
	// A float field.
	SFloat float32 `protobuf:"fixed32,14,opt,name=s_float,json=sFloat,proto3" json:"s_float,omitempty"`
	// A double field.
	SDouble       float64 `protobuf:"fixed64,15,opt,name=s_double,json=sDouble,proto3" json:"s_double,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllScalars) Reset() {
	*x = AllScalars{}
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllScalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllScalars) ProtoMessage() {}

func (x *AllScalars) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllScalars.ProtoReflect.Descriptor instead.
func (*AllScalars) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescGZIP(), []int{2}
}

func (x *AllScalars) GetSString() string {
	if x != nil {
		return x.SString
	}
	return ""
}

func (x *AllScalars) GetSBytes() []byte {
	if x != nil {
		return x.SBytes
	}
	return nil
}

func (x *AllScalars) GetSBool() bool {
	if x != nil {
		return x.SBool
	}
	return false
}

func (x *AllScalars) GetSInt32() int32 {
	if x != nil {
		return x.SInt32
	}
	return 0
}

func (x *AllScalars) GetSSint32() int32 {
	if x != nil {
		return x.SSint32
	}
	return 0
}

func (x *AllScalars) GetSSfixed32() int32 {
	if x != nil {
		return x.SSfixed32
	}
	return 0
}

func (x *AllScalars) GetSUint32() uint32 {
	if x != nil {
		return x.SUint32
	}
	return 0
}

func (x *AllScalars) GetSFixed32() uint32 {
	if x != nil {
		return x.SFixed32
	}
	return 0
}

func (x *AllScalars) GetSInt64() int64 {
	if x != nil {
		return x.SInt64
	}
	return 0
}

func (x *AllScalars) GetSSint64() int64 {
	if x != nil {
		return x.SSint64
	}
	return 0
}

func (x *AllScalars) GetSSfixed64() int64 {
	if x != nil {
		return x.SSfixed64
	}
	return 0
}

func (x *AllScalars) GetSUint64() uint64 {
	if x != nil {
		return x.SUint64
	}
	return 0
}

func (x *AllScalars) GetSFixed64() uint64 {
	if x != nil {
		return x.SFixed64
	}
	return 0
}

func (x *AllScalars) GetSFloat() float32 {
	if x != nil {
		return x.SFloat
	}
	return 0
}

func (x *AllScalars) GetSDouble() float64 {
	if x != nil {
		return x.SDouble
	}
	return 0
}

// SchemaTestMessage is the top-level request message used to test the
// schema builder: it exercises every row of the schema table in the issue.
type SchemaTestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A plain string field.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A repeated scalar field.
	Numbers []int32 `protobuf:"varint,2,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	// A map from string to an int32.
	Counts map[string]int32 `protobuf:"bytes,3,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// A map from string to a message.
	NamedInners map[string]*Inner `protobuf:"bytes,4,rep,name=named_inners,json=namedInners,proto3" json:"named_inners,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A map from string to an enum.
	ColorByName map[string]Color `protobuf:"bytes,23,rep,name=color_by_name,json=colorByName,proto3" json:"color_by_name,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=schemapb.Color"`
	// A nested (non-recursive) message field.
	Inner *Inner `protobuf:"bytes,5,opt,name=inner,proto3" json:"inner,omitempty"`
	// A recursive message field.
	Root *Node `protobuf:"bytes,6,opt,name=root,proto3" json:"root,omitempty"`
	// An enum field.
	FavoriteColor Color `protobuf:"varint,7,opt,name=favorite_color,json=favoriteColor,proto3,enum=schemapb.Color" json:"favorite_color,omitempty"`
	// A repeated enum field.
	Colors []Color `protobuf:"varint,8,rep,packed,name=colors,proto3,enum=schemapb.Color" json:"colors,omitempty"`
	// A proto3 optional field: never required.
	Nickname *string `protobuf:"bytes,9,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	// A oneof: its members are normal properties, never required.
	//
	// Types that are valid to be assigned to Contact:
	//
	//	*SchemaTestMessage_Email
	//	*SchemaTestMessage_Phone
	Contact              isSchemaTestMessage_Contact `protobuf_oneof:"contact"`
	CreatedAt            *timestamppb.Timestamp      `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ttl                  *durationpb.Duration        `protobuf:"bytes,13,opt,name=ttl,proto3" json:"ttl,omitempty"`
	NicknameWrapper      *wrapperspb.StringValue     `protobuf:"bytes,14,opt,name=nickname_wrapper,json=nicknameWrapper,proto3" json:"nickname_wrapper,omitempty"`
	CountWrapper         *wrapperspb.Int32Value      `protobuf:"bytes,15,opt,name=count_wrapper,json=countWrapper,proto3" json:"count_wrapper,omitempty"`
	FlagWrapper          *wrapperspb.BoolValue       `protobuf:"bytes,16,opt,name=flag_wrapper,json=flagWrapper,proto3" json:"flag_wrapper,omitempty"`
	BlobWrapper          *wrapperspb.BytesValue      `protobuf:"bytes,17,opt,name=blob_wrapper,json=blobWrapper,proto3" json:"blob_wrapper,omitempty"`
	Metadata             *structpb.Struct            `protobuf:"bytes,18,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AnyValue             *structpb.Value             `protobuf:"bytes,19,opt,name=any_value,json=anyValue,proto3" json:"any_value,omitempty"`
	AnyList              *structpb.ListValue         `protobuf:"bytes,20,opt,name=any_list,json=anyList,proto3" json:"any_list,omitempty"`
	UpdateMask           *fieldmaskpb.FieldMask      `protobuf:"bytes,21,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Nothing              *emptypb.Empty              `protobuf:"bytes,22,opt,name=nothing,proto3" json:"nothing,omitempty"`
	ScoreWrapper         *wrapperspb.DoubleValue     `protobuf:"bytes,24,opt,name=score_wrapper,json=scoreWrapper,proto3" json:"score_wrapper,omitempty"`
	RatioWrapper         *wrapperspb.FloatValue      `protobuf:"bytes,25,opt,name=ratio_wrapper,json=ratioWrapper,proto3" json:"ratio_wrapper,omitempty"`
	BigCountWrapper      *wrapperspb.Int64Value      `protobuf:"bytes,26,opt,name=big_count_wrapper,json=bigCountWrapper,proto3" json:"big_count_wrapper,omitempty"`
	BigUnsignedWrapper   *wrapperspb.UInt64Value     `protobuf:"bytes,27,opt,name=big_unsigned_wrapper,json=bigUnsignedWrapper,proto3" json:"big_unsigned_wrapper,omitempty"`
	SmallUnsignedWrapper *wrapperspb.UInt32Value     `protobuf:"bytes,28,opt,name=small_unsigned_wrapper,json=smallUnsignedWrapper,proto3" json:"small_unsigned_wrapper,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SchemaTestMessage) Reset() {
	*x = SchemaTestMessage{}
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaTestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaTestMessage) ProtoMessage() {}

func (x *SchemaTestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaTestMessage.ProtoReflect.Descriptor instead.
func (*SchemaTestMessage) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescGZIP(), []int{3}
}

func (x *SchemaTestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaTestMessage) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *SchemaTestMessage) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *SchemaTestMessage) GetNamedInners() map[string]*Inner {
	if x != nil {
		return x.NamedInners
	}
	return nil
}

func (x *SchemaTestMessage) GetColorByName() map[string]Color {
	if x != nil {
		return x.ColorByName
	}
	return nil
}

func (x *SchemaTestMessage) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *SchemaTestMessage) GetRoot() *Node {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *SchemaTestMessage) GetFavoriteColor() Color {
	if x != nil {
		return x.FavoriteColor
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *SchemaTestMessage) GetColors() []Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *SchemaTestMessage) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *SchemaTestMessage) GetContact() isSchemaTestMessage_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *SchemaTestMessage) GetEmail() string {
	if x != nil {
		if x, ok := x.Contact.(*SchemaTestMessage_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *SchemaTestMessage) GetPhone() string {
	if x != nil {
		if x, ok := x.Contact.(*SchemaTestMessage_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *SchemaTestMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SchemaTestMessage) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *SchemaTestMessage) GetNicknameWrapper() *wrapperspb.StringValue {
	if x != nil {
		return x.NicknameWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetCountWrapper() *wrapperspb.Int32Value {
	if x != nil {
		return x.CountWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetFlagWrapper() *wrapperspb.BoolValue {
	if x != nil {
		return x.FlagWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetBlobWrapper() *wrapperspb.BytesValue {
	if x != nil {
		return x.BlobWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SchemaTestMessage) GetAnyValue() *structpb.Value {
	if x != nil {
		return x.AnyValue
	}
	return nil
}

func (x *SchemaTestMessage) GetAnyList() *structpb.ListValue {
	if x != nil {
		return x.AnyList
	}
	return nil
}

func (x *SchemaTestMessage) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *SchemaTestMessage) GetNothing() *emptypb.Empty {
	if x != nil {
		return x.Nothing
	}
	return nil
}

func (x *SchemaTestMessage) GetScoreWrapper() *wrapperspb.DoubleValue {
	if x != nil {
		return x.ScoreWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetRatioWrapper() *wrapperspb.FloatValue {
	if x != nil {
		return x.RatioWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetBigCountWrapper() *wrapperspb.Int64Value {
	if x != nil {
		return x.BigCountWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetBigUnsignedWrapper() *wrapperspb.UInt64Value {
	if x != nil {
		return x.BigUnsignedWrapper
	}
	return nil
}

func (x *SchemaTestMessage) GetSmallUnsignedWrapper() *wrapperspb.UInt32Value {
	if x != nil {
		return x.SmallUnsignedWrapper
	}
	return nil
}

type isSchemaTestMessage_Contact interface {
	isSchemaTestMessage_Contact()
}

type SchemaTestMessage_Email struct {
	// Email address.
	Email string `protobuf:"bytes,10,opt,name=email,proto3,oneof"`
}

type SchemaTestMessage_Phone struct {
	// Phone number.
	Phone string `protobuf:"bytes,11,opt,name=phone,proto3,oneof"`
}

func (*SchemaTestMessage_Email) isSchemaTestMessage_Contact() {}

func (*SchemaTestMessage_Phone) isSchemaTestMessage_Contact() {}

var File_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto protoreflect.FileDescriptor

const file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDesc = "" +
	"\n" +
	"4cmd/protoc-gen-go-mcp/testdata/schemapb/schema.proto\x12\bschemapb\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"H\n" +
	"\x04Node\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12*\n" +
	"\bchildren\x18\x02 \x03(\v2\x0e.schemapb.NodeR\bchildren\"\x1b\n" +
	"\x05Inner\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa1\x03\n" +
	"\n" +
	"AllScalars\x12\x19\n" +
	"\bs_string\x18\x01 \x01(\tR\asString\x12\x17\n" +
	"\as_bytes\x18\x02 \x01(\fR\x06sBytes\x12\x15\n" +
	"\x06s_bool\x18\x03 \x01(\bR\x05sBool\x12\x17\n" +
	"\as_int32\x18\x04 \x01(\x05R\x06sInt32\x12\x19\n" +
	"\bs_sint32\x18\x05 \x01(\x11R\asSint32\x12\x1d\n" +
	"\n" +
	"s_sfixed32\x18\x06 \x01(\x0fR\tsSfixed32\x12\x19\n" +
	"\bs_uint32\x18\a \x01(\rR\asUint32\x12\x1b\n" +
	"\ts_fixed32\x18\b \x01(\aR\bsFixed32\x12\x17\n" +
	"\as_int64\x18\t \x01(\x03R\x06sInt64\x12\x19\n" +
	"\bs_sint64\x18\n" +
	" \x01(\x12R\asSint64\x12\x1d\n" +
	"\n" +
	"s_sfixed64\x18\v \x01(\x10R\tsSfixed64\x12\x19\n" +
	"\bs_uint64\x18\f \x01(\x04R\asUint64\x12\x1b\n" +
	"\ts_fixed64\x18\r \x01(\x06R\bsFixed64\x12\x17\n" +
	"\as_float\x18\x0e \x01(\x02R\x06sFloat\x12\x19\n" +
	"\bs_double\x18\x0f \x01(\x01R\asDouble\"\x8b\x0e\n" +
	"\x11SchemaTestMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\anumbers\x18\x02 \x03(\x05R\anumbers\x12?\n" +
	"\x06counts\x18\x03 \x03(\v2'.schemapb.SchemaTestMessage.CountsEntryR\x06counts\x12O\n" +
	"\fnamed_inners\x18\x04 \x03(\v2,.schemapb.SchemaTestMessage.NamedInnersEntryR\vnamedInners\x12P\n" +
	"\rcolor_by_name\x18\x17 \x03(\v2,.schemapb.SchemaTestMessage.ColorByNameEntryR\vcolorByName\x12%\n" +
	"\x05inner\x18\x05 \x01(\v2\x0f.schemapb.InnerR\x05inner\x12\"\n" +
	"\x04root\x18\x06 \x01(\v2\x0e.schemapb.NodeR\x04root\x126\n" +
	"\x0efavorite_color\x18\a \x01(\x0e2\x0f.schemapb.ColorR\rfavoriteColor\x12'\n" +
	"\x06colors\x18\b \x03(\x0e2\x0f.schemapb.ColorR\x06colors\x12\x1f\n" +
	"\bnickname\x18\t \x01(\tH\x01R\bnickname\x88\x01\x01\x12\x16\n" +
	"\x05email\x18\n" +
	" \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\v \x01(\tH\x00R\x05phone\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12+\n" +
	"\x03ttl\x18\r \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12G\n" +
	"\x10nickname_wrapper\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\x0fnicknameWrapper\x12@\n" +
	"\rcount_wrapper\x18\x0f \x01(\v2\x1b.google.protobuf.Int32ValueR\fcountWrapper\x12=\n" +
	"\fflag_wrapper\x18\x10 \x01(\v2\x1a.google.protobuf.BoolValueR\vflagWrapper\x12>\n" +
	"\fblob_wrapper\x18\x11 \x01(\v2\x1b.google.protobuf.BytesValueR\vblobWrapper\x123\n" +
	"\bmetadata\x18\x12 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x123\n" +
	"\tany_value\x18\x13 \x01(\v2\x16.google.protobuf.ValueR\banyValue\x125\n" +
	"\bany_list\x18\x14 \x01(\v2\x1a.google.protobuf.ListValueR\aanyList\x12;\n" +
	"\vupdate_mask\x18\x15 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x120\n" +
	"\anothing\x18\x16 \x01(\v2\x16.google.protobuf.EmptyR\anothing\x12A\n" +
	"\rscore_wrapper\x18\x18 \x01(\v2\x1c.google.protobuf.DoubleValueR\fscoreWrapper\x12@\n" +
	"\rratio_wrapper\x18\x19 \x01(\v2\x1b.google.protobuf.FloatValueR\fratioWrapper\x12G\n" +
	"\x11big_count_wrapper\x18\x1a \x01(\v2\x1b.google.protobuf.Int64ValueR\x0fbigCountWrapper\x12N\n" +
	"\x14big_unsigned_wrapper\x18\x1b \x01(\v2\x1c.google.protobuf.UInt64ValueR\x12bigUnsignedWrapper\x12R\n" +
	"\x16small_unsigned_wrapper\x18\x1c \x01(\v2\x1c.google.protobuf.UInt32ValueR\x14smallUnsignedWrapper\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aO\n" +
	"\x10NamedInnersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.schemapb.InnerR\x05value:\x028\x01\x1aO\n" +
	"\x10ColorByNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\x0e2\x0f.schemapb.ColorR\x05value:\x028\x01B\t\n" +
	"\acontactB\v\n" +
	"\t_nickname*N\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOLOR_RED\x10\x01\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\x02\x12\x0e\n" +
	"\n" +
	"COLOR_BLUE\x10\x03B2Z0cmd/protoc-gen-go-mcp/testdata/schemapb;schemapbb\x06proto3"

var (
	file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescData []byte
)

func file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDesc), len(file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDesc)))
	})
	return file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDescData
}

var file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_goTypes = []any{
	(Color)(0),                     // 0: schemapb.Color
	(*Node)(nil),                   // 1: schemapb.Node
	(*Inner)(nil),                  // 2: schemapb.Inner
	(*AllScalars)(nil),             // 3: schemapb.AllScalars
	(*SchemaTestMessage)(nil),      // 4: schemapb.SchemaTestMessage
	nil,                            // 5: schemapb.SchemaTestMessage.CountsEntry
	nil,                            // 6: schemapb.SchemaTestMessage.NamedInnersEntry
	nil,                            // 7: schemapb.SchemaTestMessage.ColorByNameEntry
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 9: google.protobuf.Duration
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
	(*wrapperspb.BoolValue)(nil),   // 12: google.protobuf.BoolValue
	(*wrapperspb.BytesValue)(nil),  // 13: google.protobuf.BytesValue
	(*structpb.Struct)(nil),        // 14: google.protobuf.Struct
	(*structpb.Value)(nil),         // 15: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 16: google.protobuf.ListValue
	(*fieldmaskpb.FieldMask)(nil),  // 17: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),          // 18: google.protobuf.Empty
	(*wrapperspb.DoubleValue)(nil), // 19: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 20: google.protobuf.FloatValue
	(*wrapperspb.Int64Value)(nil),  // 21: google.protobuf.Int64Value
	(*wrapperspb.UInt64Value)(nil), // 22: google.protobuf.UInt64Value
	(*wrapperspb.UInt32Value)(nil), // 23: google.protobuf.UInt32Value
}
var file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_depIdxs = []int32{
	1,  // 0: schemapb.Node.children:type_name -> schemapb.Node
	5,  // 1: schemapb.SchemaTestMessage.counts:type_name -> schemapb.SchemaTestMessage.CountsEntry
	6,  // 2: schemapb.SchemaTestMessage.named_inners:type_name -> schemapb.SchemaTestMessage.NamedInnersEntry
	7,  // 3: schemapb.SchemaTestMessage.color_by_name:type_name -> schemapb.SchemaTestMessage.ColorByNameEntry
	2,  // 4: schemapb.SchemaTestMessage.inner:type_name -> schemapb.Inner
	1,  // 5: schemapb.SchemaTestMessage.root:type_name -> schemapb.Node
	0,  // 6: schemapb.SchemaTestMessage.favorite_color:type_name -> schemapb.Color
	0,  // 7: schemapb.SchemaTestMessage.colors:type_name -> schemapb.Color
	8,  // 8: schemapb.SchemaTestMessage.created_at:type_name -> google.protobuf.Timestamp
	9,  // 9: schemapb.SchemaTestMessage.ttl:type_name -> google.protobuf.Duration
	10, // 10: schemapb.SchemaTestMessage.nickname_wrapper:type_name -> google.protobuf.StringValue
	11, // 11: schemapb.SchemaTestMessage.count_wrapper:type_name -> google.protobuf.Int32Value
	12, // 12: schemapb.SchemaTestMessage.flag_wrapper:type_name -> google.protobuf.BoolValue
	13, // 13: schemapb.SchemaTestMessage.blob_wrapper:type_name -> google.protobuf.BytesValue
	14, // 14: schemapb.SchemaTestMessage.metadata:type_name -> google.protobuf.Struct
	15, // 15: schemapb.SchemaTestMessage.any_value:type_name -> google.protobuf.Value
	16, // 16: schemapb.SchemaTestMessage.any_list:type_name -> google.protobuf.ListValue
	17, // 17: schemapb.SchemaTestMessage.update_mask:type_name -> google.protobuf.FieldMask
	18, // 18: schemapb.SchemaTestMessage.nothing:type_name -> google.protobuf.Empty
	19, // 19: schemapb.SchemaTestMessage.score_wrapper:type_name -> google.protobuf.DoubleValue
	20, // 20: schemapb.SchemaTestMessage.ratio_wrapper:type_name -> google.protobuf.FloatValue
	21, // 21: schemapb.SchemaTestMessage.big_count_wrapper:type_name -> google.protobuf.Int64Value
	22, // 22: schemapb.SchemaTestMessage.big_unsigned_wrapper:type_name -> google.protobuf.UInt64Value
	23, // 23: schemapb.SchemaTestMessage.small_unsigned_wrapper:type_name -> google.protobuf.UInt32Value
	2,  // 24: schemapb.SchemaTestMessage.NamedInnersEntry.value:type_name -> schemapb.Inner
	0,  // 25: schemapb.SchemaTestMessage.ColorByNameEntry.value:type_name -> schemapb.Color
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_init() }
func file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_init() {
	if File_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto != nil {
		return
	}
	file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes[3].OneofWrappers = []any{
		(*SchemaTestMessage_Email)(nil),
		(*SchemaTestMessage_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDesc), len(file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_depIdxs,
		EnumInfos:         file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_enumTypes,
		MessageInfos:      file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_msgTypes,
	}.Build()
	File_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto = out.File
	file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_goTypes = nil
	file_cmd_protoc_gen_go_mcp_testdata_schemapb_schema_proto_depIdxs = nil
}
