// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.3
// source: examples/protos/example.proto

package examplev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetVibeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vibe string `protobuf:"bytes,1,opt,name=vibe,proto3" json:"vibe,omitempty"`
}

func (x *SetVibeRequest) Reset() {
	*x = SetVibeRequest{}
	mi := &file_examples_protos_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVibeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVibeRequest) ProtoMessage() {}

func (x *SetVibeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVibeRequest.ProtoReflect.Descriptor instead.
func (*SetVibeRequest) Descriptor() ([]byte, []int) {
	return file_examples_protos_example_proto_rawDescGZIP(), []int{0}
}

func (x *SetVibeRequest) GetVibe() string {
	if x != nil {
		return x.Vibe
	}
	return ""
}

type SetVibeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviousVibe string `protobuf:"bytes,1,opt,name=previousVibe,proto3" json:"previousVibe,omitempty"`
	Vibe         string `protobuf:"bytes,2,opt,name=vibe,proto3" json:"vibe,omitempty"`
}

func (x *SetVibeResponse) Reset() {
	*x = SetVibeResponse{}
	mi := &file_examples_protos_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVibeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVibeResponse) ProtoMessage() {}

func (x *SetVibeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVibeResponse.ProtoReflect.Descriptor instead.
func (*SetVibeResponse) Descriptor() ([]byte, []int) {
	return file_examples_protos_example_proto_rawDescGZIP(), []int{1}
}

func (x *SetVibeResponse) GetPreviousVibe() string {
	if x != nil {
		return x.PreviousVibe
	}
	return ""
}

func (x *SetVibeResponse) GetVibe() string {
	if x != nil {
		return x.Vibe
	}
	return ""
}

type GetVibeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVibeRequest) Reset() {
	*x = GetVibeRequest{}
	mi := &file_examples_protos_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVibeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVibeRequest) ProtoMessage() {}

func (x *GetVibeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVibeRequest.ProtoReflect.Descriptor instead.
func (*GetVibeRequest) Descriptor() ([]byte, []int) {
	return file_examples_protos_example_proto_rawDescGZIP(), []int{2}
}

type GetVibeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vibe string `protobuf:"bytes,1,opt,name=vibe,proto3" json:"vibe,omitempty"`
}

func (x *GetVibeResponse) Reset() {
	*x = GetVibeResponse{}
	mi := &file_examples_protos_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVibeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVibeResponse) ProtoMessage() {}

func (x *GetVibeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVibeResponse.ProtoReflect.Descriptor instead.
func (*GetVibeResponse) Descriptor() ([]byte, []int) {
	return file_examples_protos_example_proto_rawDescGZIP(), []int{3}
}

func (x *GetVibeResponse) GetVibe() string {
	if x != nil {
		return x.Vibe
	}
	return ""
}

var File_examples_protos_example_proto protoreflect.FileDescriptor

var file_examples_protos_example_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x24, 0x0a, 0x0e,
	0x53, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x69, 0x62, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x69,
	0x62, 0x65, 0x22, 0x49, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75,
	0x73, 0x56, 0x69, 0x62, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x56, 0x69, 0x62, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x62,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x69, 0x62, 0x65, 0x22, 0x10, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x62, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x76, 0x69, 0x62, 0x65, 0x32, 0x9d, 0x01, 0x0a, 0x0b, 0x56, 0x69, 0x62, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x56, 0x69, 0x62,
	0x65, 0x12, 0x1b, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x56, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x12, 0x1b, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2f, 0x67, 0x65, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_examples_protos_example_proto_rawDescOnce sync.Once
	file_examples_protos_example_proto_rawDescData = file_examples_protos_example_proto_rawDesc
)

func file_examples_protos_example_proto_rawDescGZIP() []byte {
	file_examples_protos_example_proto_rawDescOnce.Do(func() {
		file_examples_protos_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_protos_example_proto_rawDescData)
	})
	return file_examples_protos_example_proto_rawDescData
}

var file_examples_protos_example_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_protos_example_proto_goTypes = []any{
	(*SetVibeRequest)(nil),  // 0: examples.v1.SetVibeRequest
	(*SetVibeResponse)(nil), // 1: examples.v1.SetVibeResponse
	(*GetVibeRequest)(nil),  // 2: examples.v1.GetVibeRequest
	(*GetVibeResponse)(nil), // 3: examples.v1.GetVibeResponse
}
var file_examples_protos_example_proto_depIdxs = []int32{
	0, // 0: examples.v1.VibeService.SetVibe:input_type -> examples.v1.SetVibeRequest
	2, // 1: examples.v1.VibeService.GetVibe:input_type -> examples.v1.GetVibeRequest
	1, // 2: examples.v1.VibeService.SetVibe:output_type -> examples.v1.SetVibeResponse
	3, // 3: examples.v1.VibeService.GetVibe:output_type -> examples.v1.GetVibeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_protos_example_proto_init() }
func file_examples_protos_example_proto_init() {
	if File_examples_protos_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_protos_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_protos_example_proto_goTypes,
		DependencyIndexes: file_examples_protos_example_proto_depIdxs,
		MessageInfos:      file_examples_protos_example_proto_msgTypes,
	}.Build()
	File_examples_protos_example_proto = out.File
	file_examples_protos_example_proto_rawDesc = nil
	file_examples_protos_example_proto_goTypes = nil
	file_examples_protos_example_proto_depIdxs = nil
}
