package main

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// FileDescriptorProto.package field number
const fileDescriptorProtoPackageFieldNumber = 2

// FileDescriptorProto.syntax field number
const fileDescriptorProtoSyntaxFieldNumber = 12

const contextPackage = protogen.GoImportPath("context")
const jsonPackage = protogen.GoImportPath("encoding/json")
const mcpPackage = protogen.GoImportPath("github.com/modelcontextprotocol/go-sdk/mcp")
const protojsonPackage = protogen.GoImportPath("google.golang.org/protobuf/encoding/protojson")

// generateFile generates a _mcp.pb.go file containing, for each gRPC service
// in file, an MCP server that exposes each non-streaming RPC as an MCP tool
// and forwards tool calls to a gRPC client.
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_mcp.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	// Attach all comments associated with the syntax field.
	genLeadingComments(g, file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoSyntaxFieldNumber}))
	g.P("// Code generated by protoc-gen-go-mcp. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-go-mcp v", version)
	g.P("// - protoc             ", protocVersion(gen))
	//if file.Proto.GetOptions().GetDeprecated() {
	//	g.P("// ", file.Desc.Path(), " is a deprecated file.")
	//} else {
	//	g.P("// source: ", file.Desc.Path())
	//}
	g.P()
	//// Attach all comments associated with the package field.
	genLeadingComments(g, file.Desc.SourceLocations().ByPath(protoreflect.SourcePath{fileDescriptorProtoPackageFieldNumber}))
	g.P("package ", file.GoPackageName)
	g.P()
	generateFileContent(gen, file, g)
	return g
}

func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Services) == 0 {
		return
	}
	for _, service := range file.Services {
		genMCPService(gen, file, g, service)
	}
}

func genMCPService(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service) {
	mcpServerName := service.GoName + "MCPServer"
	clientName := service.GoName + "Client"
	generateMcpServerStruct(g, mcpServerName, clientName)
	generateMcpServerService(g, service, mcpServerName, clientName)
	generateMcpServerHandlers(g, service, mcpServerName, clientName)
}

func generateMcpServerService(g *protogen.GeneratedFile, service *protogen.Service, mcpServerName string, clientName string) {
	constructorName := "New" + service.GoName + "MCPServer"
	serverStructName := unexport(mcpServerName)

	g.P("func ", constructorName, "(")
	g.P("client ", clientName, ",")
	g.P("mcpServer *", mcpPackage.Ident("Server"), ",")
	g.P(") *", serverStructName, " {")
	g.P("return &", serverStructName, "{")
	g.P("", clientName, ": client,")
	g.P("MCPServer: mcpServer,")
	g.P("}")
	g.P("}")
	g.P()
}

func generateMcpServerHandlers(g *protogen.GeneratedFile, service *protogen.Service, mcpServerName string, clientName string) {
	methods := make([]*protogen.Method, 0)
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			// Skip streaming methods
			// TODO: Evaluate support of streaming methods
		} else {
			methods = append(methods, method)
			generateMCPTool(g, method, mcpServerName)
			g.P()
			generateHandler(g, method, mcpServerName, clientName)
			g.P()
		}
	}
	g.P()
	generateToolRegistration(g, mcpServerName)
	generateDefaultToolsRegistration(g, methods, mcpServerName)
}

// generateMCPTool emits a method that builds the *mcp.Tool for method: its
// name, description (from the method's leading comment, falling back to a
// space-separated version of its Go name), and input schema (the JSON
// Schema for the request message, from MessageInputSchema, embedded as a
// json.RawMessage literal so mcp.AddTool validates arguments against it
// instead of inferring a schema from the handler's argument type).
func generateMCPTool(g *protogen.GeneratedFile, method *protogen.Method, mcpServerName string) {
	methodDescription := ""
	if len(method.Comments.Leading) > 0 {
		methodDescription = processCommentToString(method.Comments.Leading)
	} else {
		methodDescription = camelToSpace(method.GoName)
	}

	schema := MessageInputSchema(method.Input)
	schemaJSON, err := json.Marshal(schema)
	if err != nil {
		// Unreachable: schema is built entirely out of maps, slices and
		// JSON-safe scalars (see schema.go), none of which json.Marshal can
		// fail on.
		panic(fmt.Sprintf("marshaling input schema for %s: %v", method.Input.Desc.FullName(), err))
	}

	g.P("func (s *", unexport(mcpServerName), ") ", method.GoName, "Tool() *", mcpPackage.Ident("Tool"), " {")
	g.P("return &", mcpPackage.Ident("Tool"), "{")
	g.P("Name: \"", method.GoName, "\",")
	g.P("Description: ", strconv.Quote(methodDescription), ",")
	g.P("InputSchema: ", jsonPackage.Ident("RawMessage"), "(", quoteBacktickString(string(schemaJSON)), "),")
	g.P("}")
	g.P("}")
}

// generateHandler emits the typed tool handler for method: it decodes the
// raw JSON arguments into the request message with protojson.Unmarshal (the
// SDK has already validated them against the schema generateMCPTool emits),
// calls the gRPC client, and returns the response as protojson text, or the
// gRPC error as a tool error.
func generateHandler(g *protogen.GeneratedFile, method *protogen.Method, mcpServerName string, clientName string) {
	g.P("func (s *", unexport(mcpServerName), ") ", method.GoName, "Handler(ctx ", contextPackage.Ident("Context"), ", req *", mcpPackage.Ident("CallToolRequest"), ", args ", jsonPackage.Ident("RawMessage"), ") (*", mcpPackage.Ident("CallToolResult"), ", any, error) {")

	g.P("protoReq := &", g.QualifiedGoIdent(method.Input.GoIdent), "{}")
	g.P("if len(args) > 0 {")
	g.P("if err := ", protojsonPackage.Ident("Unmarshal"), "(args, protoReq); err != nil {")
	g.P("return nil, nil, err")
	g.P("}")
	g.P("}")
	g.P()

	g.P("resp, err := s.", clientName, ".", method.GoName, "(ctx, protoReq)")
	g.P("if err != nil {")
	g.P("return nil, nil, err")
	g.P("}")
	g.P()

	g.P("respJSON, err := ", protojsonPackage.Ident("Marshal"), "(resp)")
	g.P("if err != nil {")
	g.P("return nil, nil, err")
	g.P("}")
	g.P()

	g.P("return &", mcpPackage.Ident("CallToolResult"), "{")
	g.P("Content: []", mcpPackage.Ident("Content"), "{")
	g.P("&", mcpPackage.Ident("TextContent"), "{Text: string(respJSON)},")
	g.P("},")
	g.P("}, nil, nil")
	g.P("}")
}

// processCommentToString turns a (possibly multi-line, possibly
// block-style) leading proto comment into a single-line string with its
// raw text otherwise untouched: callers are responsible for escaping it
// for whatever they embed it in (a Go string literal via strconv.Quote, a
// JSON Schema "description" via encoding/json), so this never escapes
// quotes or backslashes itself - doing so here would corrupt the text when
// a caller's own encoding escapes it a second time.
func processCommentToString(comments protogen.Comments) string {
	// protogen.Comments strings for a line comment ("// foo") have the
	// "// " prefix already stripped from the first line (but not
	// continuation lines) and a trailing newline; a block comment
	// ("/* foo */") keeps its "/* " prefix and " */" suffix. Strip both
	// styles uniformly below instead of relying on that asymmetry.
	commentText := string(comments)

	commentText = strings.TrimPrefix(commentText, "// ")
	commentText = strings.TrimPrefix(commentText, "/* ")
	commentText = strings.TrimSuffix(commentText, " */")

	// Join every line (dropping any remaining "// " line-comment prefix)
	// into a single space-separated line.
	lines := strings.Split(commentText, "\n")
	for i, line := range lines {
		lines[i] = strings.TrimPrefix(line, "// ")
	}
	commentText = strings.Join(lines, " ")

	commentText = strings.TrimSpace(commentText)

	// Collapse runs of whitespace (including the spaces just introduced
	// for blank comment lines) into a single space.
	commentText = whitespaceRunRegexp.ReplaceAllString(commentText, " ")

	return commentText
}

// whitespaceRunRegexp matches one or more consecutive whitespace
// characters, used by processCommentToString to collapse them to a single
// space.
var whitespaceRunRegexp = regexp.MustCompile(`\s+`)

func generateMcpServerStruct(g *protogen.GeneratedFile, mcpServerName string, clientName string) {
	g.P("type ", unexport(mcpServerName), " struct {")
	g.P(clientName)
	g.P()
	g.P("MCPServer ", QualifiedGoIdentPointer(g, mcpPackage.Ident("Server")))
	g.P("}")
	g.P()
}

func generateDefaultToolsRegistration(g *protogen.GeneratedFile, methods []*protogen.Method, mcpServerName string) {
	g.P("func (s *", unexport(mcpServerName), ") RegisterDefaultTools() {")
	for _, method := range methods {
		g.P("s.RegisterTool(s.", method.GoName, "Tool(), s.", method.GoName, "Handler)")
	}
	g.P("}")
	g.P()
}

// generateToolRegistration emits a RegisterTool method that registers a
// tool and its typed handler with mcp.AddTool, so the SDK validates
// arguments against the tool's input schema before the handler ever runs
// (the raw Server.AddTool does not validate).
func generateToolRegistration(g *protogen.GeneratedFile, mcpServerName string) {
	g.P("func (s *", unexport(mcpServerName), ") RegisterTool(tool *", mcpPackage.Ident("Tool"), ", handler ", mcpPackage.Ident("ToolHandlerFor"), "[", jsonPackage.Ident("RawMessage"), ", any]) {")
	g.P(mcpPackage.Ident("AddTool"), "(s.MCPServer, tool, handler)")
	g.P("}")
	g.P()
}

// QualifiedGoIdentPointer returns the string to use for a Go identifier as a pointer type.
//
// If the identifier is from a different Go package than the generated file,
// the returned name will be qualified (package.name) and an import statement
// for the identifier's package will be included in the file.
func QualifiedGoIdentPointer(g *protogen.GeneratedFile, ident protogen.GoIdent) string {
	return "*" + g.QualifiedGoIdent(ident)
}

func unexport(s string) string {
	name := strings.ToLower(s[:1])

	if len(s) > 1 {
		name += s[1:]
	}

	return name
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func genLeadingComments(g *protogen.GeneratedFile, loc protoreflect.SourceLocation) {
	for _, s := range loc.LeadingDetachedComments {
		g.P(protogen.Comments(s))
	}
	if s := loc.LeadingComments; s != "" {
		g.P(protogen.Comments(s))
	}
}

func camelToSpace(s string) string {
	re := regexp.MustCompile(`([a-zA-Z])([0-9])|([0-9])([a-zA-Z])|([a-z])([A-Z])`)
	return re.ReplaceAllStringFunc(s, func(match string) string {
		// Handle lowercase to uppercase (e.g., myValue → my Value)
		re1 := regexp.MustCompile(`([a-z])([A-Z])`)
		match = re1.ReplaceAllString(match, `$1 $2`)

		// Handle letter to number (e.g., item123 → item 123)
		re2 := regexp.MustCompile(`([a-zA-Z])([0-9])`)
		match = re2.ReplaceAllString(match, `$1 $2`)

		// Handle number to letter (e.g., 123item → 123 item)
		re3 := regexp.MustCompile(`([0-9])([a-zA-Z])`)
		match = re3.ReplaceAllString(match, `$1 $2`)

		return match
	})
}

// quoteBacktickString returns a Go string literal for s, preferring a
// backtick-quoted raw string (readable for embedded JSON) unless s itself
// contains a backtick, in which case it falls back to strconv.Quote.
func quoteBacktickString(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}
